// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_TphyXuRtY_fWolM4g4eeHND879wARE',
    appId: '1:504905958841:web:54ca6e80813e093cd82268',
    messagingSenderId: '504905958841',
    projectId: 'flutterapp-421b3',
    authDomain: 'flutterapp-421b3.firebaseapp.com',
    storageBucket: 'flutterapp-421b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUoTLGfWXyJnQHFsb5vjb6UOYmoh_HfKI',
    appId: '1:504905958841:android:233a5e0376fda1bdd82268',
    messagingSenderId: '504905958841',
    projectId: 'flutterapp-421b3',
    storageBucket: 'flutterapp-421b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX0cWbrOUWvGXl_VKmH-bnvBp5ZTQsN_w',
    appId: '1:504905958841:ios:c5eab6b911e2813cd82268',
    messagingSenderId: '504905958841',
    projectId: 'flutterapp-421b3',
    storageBucket: 'flutterapp-421b3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX0cWbrOUWvGXl_VKmH-bnvBp5ZTQsN_w',
    appId: '1:504905958841:ios:c5eab6b911e2813cd82268',
    messagingSenderId: '504905958841',
    projectId: 'flutterapp-421b3',
    storageBucket: 'flutterapp-421b3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa_TphyXuRtY_fWolM4g4eeHND879wARE',
    appId: '1:504905958841:web:6eb0c8c1d3378fdcd82268',
    messagingSenderId: '504905958841',
    projectId: 'flutterapp-421b3',
    authDomain: 'flutterapp-421b3.firebaseapp.com',
    storageBucket: 'flutterapp-421b3.firebasestorage.app',
  );
}
